[[manager.prepend_keymap]]
on  = "y"
run = [ 'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list', "yank" ]

[[manager.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- dragon-drop -x -i -T "$1"'
